# 1. yaml格式的文件, 也是使用#来添加注释
# 2. 每一个区域下的选项缩进要一致, 推荐缩进两个空格
excel:
    cases_path: "cases.xlsx"
    result_col: 8
    actual_col: 7
msg:
  success_result: Success
  fail_result: Fail
log:
  log_name: cases
  logger_level: DEBUG
  formatter: '%(asctime)s - [%(filename)s-->line:%(lineno)d] - %(levelname)s: %(message)s'
  stream_level: DEBUG
  logfile_name: test.log
  logfile_level: DEBUG
report:
  name: report
  title: "贸驰接口自动化测试报告"
  description: "完美的报告"
  tester: "song"
mysql:
  host: 'rm-8vbch9r86sk1h4t6h6o.mysql.zhangbei.rds.aliyuncs.com'
  user: 'more_chips'
  password: '1qaz@WSX'
  db: 'morechips'
  port: 3306
  select_user_sql: "SELECT * FROM member WHERE mobile_phone = %s ;"
  select_userid_sql: "SELECT id FROM sys_user WHERE mobile_phone = %s ;"
  select_product_id: "select id FROM bus_product ORDER BY id DESC LIMIT 0,1 ;"
api:
  #version: {"X-Lemonban-Media-Type": "lemonban.v2"}
  prefix: "http://106.12.56.107:9101"
  version: {"Content-Type": "application/json;charset=UTF-8"}
